Web/Controllers/ApplicationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;
using Microsoft.AspNet.Identity;

namespace Web.Controllers
{
    public class ApplicationsController : Controller
    {
        private DevJobBoardEntities db = new DevJobBoardEntities();

        // GET: Applications
        public ActionResult Index()
        {
            #region Foo

            List<Application> app = new List<Application>();
            List<Location> loc = new List<Location>();
            List<OpenPosition> op = new List<OpenPosition>();

            if (User.IsInRole("User"))
            {
                foreach (var item in db.Applications)
                {
                    if (item.UserID == User.Identity.GetUserId())
                    {
                        app.Add(item);
                    }
                }


                return View(app);
            }

            if (User.IsInRole("Company"))
            {
                foreach (var item in db.Locations)
                {
                    //matches current (company)user's ID to CompanyIDs in the Location table
                    if (item.CompanyID == User.Identity.GetUserId())
                    {
                        // Add items that do have right ID to the collection
                        loc.Add(item);
                    }
                }
                foreach (var item in db.OpenPositions)
                {
                    //for each ID from above
                    foreach (var iteml in loc)
                    {
                        // Matchs up CompanyIDs from l collection to what's currently in OpenPositions
                        if (item.LocationID == iteml.LocationID)
                        {
                            // Add items from OpenPositions that have same ID as (company)user
                            op.Add(item);
                        }
                    }
                }
                foreach (var item in db.Applications)
                {
                    //for each ID from above
                    foreach (var itemo in op)
                    {
                        // Matchs up CompanyIDs from l collection to what's currently in OpenPositions
                        if (item.OpenPositionID == itemo.OpenPositionID)
                        {
                            // Add items from OpenPositions that have same ID as (company)user
                            app.Add(item);
                        }
                    }
                }
                // Return view with only matching ids
                return View(app);
            }
            #endregion



            var applications = db.Applications.Include(a => a.OpenPosition);
            return View(applications.ToList());
        }

        // GET: Applications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // GET: Applications/Create
        public ActionResult Create()
        {
            ViewBag.OpenPositionID = new SelectList(db.OpenPositions, "OpenPositionID", "OpenPositionID");
            return View();
        }

        // POST: Applications/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ApplicationID,OpenPositionID,UserID,ApplicationDate,ManagerNotes,IsDeclined,ResumeFilename")] Application application)
        {
            if (ModelState.IsValid)
            {
                db.Applications.Add(application);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.OpenPositionID = new SelectList(db.OpenPositions, "OpenPositionID", "OpenPositionID", application.OpenPositionID);
            return View(application);
        }

        // GET: Applications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            ViewBag.OpenPositionID = new SelectList(db.OpenPositions, "OpenPositionID", "OpenPositionID", application.OpenPositionID);
            return View(application);
        }

        // POST: Applications/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ApplicationID,OpenPositionID,UserID,ApplicationDate,ManagerNotes,IsDeclined,ResumeFilename")] Application application)
        {
            if (ModelState.IsValid)
            {
                db.Entry(application).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.OpenPositionID = new SelectList(db.OpenPositions, "OpenPositionID", "OpenPositionID", application.OpenPositionID);
            return View(application);
        }

        // GET: Applications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Application application = db.Applications.Find(id);
            if (application == null)
            {
                return HttpNotFound();
            }
            return View(application);
        }

        // POST: Applications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Application application = db.Applications.Find(id);
            db.Applications.Remove(application);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Apply(int OpenPositionID)
        {
            Application app = new Application();
            UserDetail user = new UserDetail();
            string ppl = User.Identity.GetUserId();
            user = db.UserDetails.Where(x => x.UserID == ppl).Single();

            app.OpenPositionID = OpenPositionID;
            app.UserID = User.Identity.GetUserId();
            app.ResumeFilename = user.ResumeFilename;
            app.ApplicationDate = DateTime.Now;

            db.Applications.Add(app);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Web/Controllers/OpenPositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;
using Microsoft.AspNet.Identity;

namespace Web.Controllers
{
    public class OpenPositionsController : Controller
    {
        private DevJobBoardEntities db = new DevJobBoardEntities();

        // GET: OpenPositions
        public ActionResult Index()
        {


            #region User specific viewing privelages
            List<OpenPosition> op = new List<OpenPosition>();
            List<Location> l = new List<Location>();
            if (User.IsInRole("Company"))
            {
            foreach (var item in db.Locations)
            {
                //matches current (company)user's ID to CompanyIDs in the Location table
                if (item.CompanyID == User.Identity.GetUserId())
                {
                    // Add items that do have right ID to the collection
                    l.Add(item);
                }
            }

            foreach (var item in db.OpenPositions)
            {
                //for each ID from above
                foreach (var iteml in l)
                {
                    // Matchs up CompanyIDs from l collection to what's currently in OpenPositions
                    if (item.LocationID == iteml.LocationID)
                    {
                        // Add items from OpenPositions that have same ID as (company)user
                        op.Add(item);                
                    }
                }
            }
            // Return view with only matching ids
            return View(op);
            }
                #endregion

                var openPositions = db.OpenPositions.Include(o => o.Location).Include(o => o.Position);
            return View(openPositions.ToList());
        }

        // GET: OpenPositions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            return View(openPosition);
        }

        // GET: OpenPositions/Create
        public ActionResult Create()
        {
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "CompanyName");
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "Title");
            return View();
        }

        // POST: OpenPositions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OpenPositionID,PositionID,LocationID")] OpenPosition openPosition)
        {
            if (ModelState.IsValid)
            {
                string foo = User.Identity.GetUserId();
                openPosition.LocationID = db.Locations.Where(x => x.CompanyID == foo).Select(x => x.LocationID).Single();
                

                db.OpenPositions.Add(openPosition);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "CompanyName", openPosition.LocationID);
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "Title", openPosition.PositionID);
            return View(openPosition);
        }

        // GET: OpenPositions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "CompanyName", openPosition.LocationID);
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "Title", openPosition.PositionID);
            return View(openPosition);
        }

        // POST: OpenPositions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "OpenPositionID,PositionID,LocationID")] OpenPosition openPosition)
        {
            if (ModelState.IsValid)
            {
                db.Entry(openPosition).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.LocationID = new SelectList(db.Locations, "LocationID", "CompanyName", openPosition.LocationID);
            ViewBag.PositionID = new SelectList(db.Positions, "PositionID", "Title", openPosition.PositionID);
            return View(openPosition);
        }

        // GET: OpenPositions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            OpenPosition openPosition = db.OpenPositions.Find(id);
            if (openPosition == null)
            {
                return HttpNotFound();
            }
            return View(openPosition);
        }

        // POST: OpenPositions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            OpenPosition openPosition = db.OpenPositions.Find(id);
            db.OpenPositions.Remove(openPosition);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult CompanyPositions()
        {
            return View();
        }
    }
}

Web/Controllers/PositionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Data;

namespace Web.Controllers
{
    public class PositionsController : Controller
    {
        private DevJobBoardEntities db = new DevJobBoardEntities();

        // GET: Positions
        public ActionResult Index()
        {
            return View(db.Positions.ToList());
        }

        // GET: Positions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // GET: Positions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Positions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PositionID,Title,JobDescription")] Position position)
        {
            if (ModelState.IsValid)
            {
                db.Positions.Add(position);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(position);
        }

        // GET: Positions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Positions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PositionID,Title,JobDescription")] Position position)
        {
            if (ModelState.IsValid)
            {
                db.Entry(position).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(position);
        }

        // GET: Positions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Position position = db.Positions.Find(id);
            if (position == null)
            {
                return HttpNotFound();
            }
            return View(position);
        }

        // POST: Positions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Position position = db.Positions.Find(id);
            db.Positions.Remove(position);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/Views/OpenPositions/CompanyPositions.cshtml
@{
    ViewBag.Title = "Listing Manager";
    ViewBag.Header = "Manage and view listings for positions at your company";
}



<div class="container">
    <br />
    <h2 class="text-center">Your Options</h2>
    <br />
    <div class="row">
        <div class="col-md-6">
            <h2 class="text-center"><a href="@Url.Action("Create", "OpenPositions")">Make New Listing</a></h2>
            <hr />
            <p class="lead text-center"> Put out a new listing for a position you would like to be filled at your Company/Studio. </p>

            <h2 class="text-center">OR</h2>

            <h2 class="text-center"><a href="@Url.Action("Create", "Positions")">Make New Position</a></h2>
            <hr />
            <p class="lead text-center"> Create a new Title & Job Description for a position you would like to make a listing for. </p>

            <br />
        </div>
        <div class="col-md-6">
            <h2 class="text-center"><a href="@Url.Action("Index", "OpenPositions")">View Positions Listed</a></h2>
            <hr />
            <p class="lead text-center">Here is where your current, publicly listed positions are posted. </p>
            <br />
        </div>
    </div>
    
</div>

Web/Views/OpenPositions/Create.cshtml
@model Data.OpenPosition

@{
    ViewBag.Title = "Listing Manager";
    ViewBag.Header = "Make a listing for a position you'd like filled at your company";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <br />
    <div class="form-horizontal">
        <br />
        <h2 class="title text-center">What position do you want to list?</h2>
        <hr class="star-dark mb-5">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group col-md-12">
            
            <div class="col-md-6 offset-3 text-center">
                @Html.DropDownList("PositionID", null, htmlAttributes: new { @class = "form-control align-content-center" })
                @Html.ValidationMessageFor(model => model.PositionID, "", new { @class = "text-danger align-content-center" })
            </div>
        </div>

        <div class="form-group">
            <div class="offset-4 col-md-12">
                <input type="submit" value="Post Listing" class="btn btn-dark" />
                <a href="@Url.Action("Create", "Positions")" class="btn btn-dark"> Need to make a new position?</a>
            </div>
        </div>
    </div>
}

<!-- Maybe do something with this later -->
@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@

Web/Views/OpenPositions/Delete.cshtml
@model Data.OpenPosition

@{
    ViewBag.Title = "Delete Confirmation";
}

<br />

<h3 class="text-center">Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal text-center" style="font-size: 2em;">


        <dd style="color: red;">
            @Html.DisplayFor(model => model.Location.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.JobDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.JobDescription)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Web/Views/OpenPositions/Details.cshtml
@model Data.OpenPosition

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>OpenPosition</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Location.CompanyName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location.CompanyName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position.Title)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.OpenPositionID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Web/Views/OpenPositions/Edit.cshtml
@model Data.OpenPosition

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>OpenPosition</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.OpenPositionID)

        <div class="form-group">
            @Html.LabelFor(model => model.PositionID, "PositionID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PositionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PositionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocationID, "LocationID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LocationID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LocationID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Web/Views/OpenPositions/Index.cshtml
@model IEnumerable<Data.OpenPosition>
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = "Positions";
    ViewBag.Header = "Your currently listed positions";


    if (!User.IsInRole("Company"))
    {
        ViewBag.Title = "Open Positions";
        ViewBag.Header = "Apply to listings below";
    }


}

@if (User.IsInRole("Company"))
{
    <a class="btn btn-xl btn-outline-dark" href="@Url.Action("CompanyPositions", "OpenPositions")">
        <i class="fa fa-plus-circle mr-2"></i>
        Make New Position
    </a>
}


@*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Location.CompanyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position.JobDescription)
            </th>
            <th></th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Location.CompanyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location.CompanyPic)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position.JobDescription)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.OpenPositionID }) |
                @Html.ActionLink("Details", "Details", new { id=item.OpenPositionID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.OpenPositionID })
            </td>
        </tr>
    }

</table>*@

<section class="portfolio" id="portfolio">
    <div class="container">
        @*<h2 class="text-center text-uppercase text-secondary mb-0">Open Positions</h2>
        <hr class="star-dark mb-5">*@
        <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-md-6 col-lg-4">
                <a class="portfolio-item d-block mx-auto" href="#portfolio-modal-@item.OpenPositionID">
                    <div class="portfolio-item-caption d-flex position-absolute h-100 w-100">
                        <div class="portfolio-item-caption-content my-auto w-100 text-center text-white">
                            <i class="fa fa-window-maximize fa-3x"></i>
                        </div>
                    </div>
                    <img class="img-fluid" style="width: 100%; height: 340px; object-fit:fill;" src="@Url.Content("~/Content/img/Companies/" + @item.Location.CompanyPic)" alt="@item.Location.CompanyPic">
                    <div style="background-color : whitesmoke">
                        <p span style="font-size: 1.5em !important;" class="text-center">@Html.DisplayFor(modelItem => item.Position.Title)</p>
                        <p span style="font-size: 1.1em !important; color: darkgrey;" class="text-center">@Html.DisplayFor(modelItem => item.Location.CompanyName)</p>
                    </div>
                </a>
            </div>
        }
        </div>
    </div>
</section>

<!-- Modals -->
@foreach (var item in Model)
{
<div class="portfolio-modal mfp-hide" id="portfolio-modal-@item.OpenPositionID">
    <div class="portfolio-modal-dialog bg-white">
        <a class="close-button d-none d-md-block portfolio-modal-dismiss" href="#">
            <i class="fa fa-3x fa-times"></i>
        </a>
        <div class="container text-center">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <h2 class="text-secondary text-uppercase mb-0">@Html.DisplayFor(modelItem => item.Position.Title)</h2>
                    <hr class="star-dark mb-5">
                    <img class="img-fluid mb-5" style="width: 100%; height: 500px; object-fit:fill;" src="@Url.Content("~/Content/img/Companies/" + @item.Location.CompanyPic)" alt="">
                    <p class="mb-5" style="font-size: 1.6em;">@Html.DisplayFor(modelItem => item.Position.JobDescription)</p>

                    <p class="mb-5" style="font-size: 1.6em; color:darkseagreen;">@Html.DisplayFor(modelItem => item.Location.City), @Html.DisplayFor(modelItem => item.Location.State)</p>
                    <a class="btn btn-primary btn-lg rounded-pill pull-left" href="@Url.Action("Apply", "Applications", new { OpenPositionID = item.OpenPositionID }) ">
                        <i class="fa fa-close"></i>
                        Apply for Position <i class="fa fa-check" aria-hidden="true"></i>
                    </a>
                    
                    @if (!User.IsInRole("User"))
                    {
                        <a class="btn btn-primary btn-lg rounded-pill pull-left" href="@Url.Action("Delete", new { id = item.OpenPositionID }) ">
                            <i class="fa fa-close"></i>
                            Delete this Listing <i class="fa fa-times-circle" aria-hidden="true"></i>
                        </a>
                    }
                    <a class="btn btn-primary btn-lg rounded-pill portfolio-modal-dismiss pull-right" href="#">
                        <i class="fa fa-close"></i>
                        Close Position
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
}